version: "3"
services:
  backend:
    build: .
    container_name: car-backend-container
    ports:
      - "8089:8089"
    volumes:
      - shared-data:/shared-data

  data-preprocessing:
    build: .
    container_name: data-preprocessing-container
    command:
      [
        "sh",
        "-c",
        "while true; do python data_preprocessing.py; sleep 3600; done",
      ]
    volumes:
      - shared-data:/shared-data

  scraper:
    build: ./../car-scraper
    container_name: car-scraper-container
    ports: "9090:9090"
    volumes:
      - shared-data:/shared-data

volumes:
  shared-data:
