FROM python:3.9

# 작업 디렉토리 설정
WORKDIR /app

# 소스 복사
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements-worker.txt

# cron 설치 및 설정
RUN apt-get update && apt-get install -y cron

# 스케줄러 파일 복사
COPY cronJob /etc/cron.d/data-preprocessing-cron

# cron 권한 설정
RUN chmod 0644 /etc/cron.d/data-preprocessing-cron

# cron 등록
RUN crontab /etc/cron.d/data-preprocessing-cron

# cron 시작
CMD ["cron", "-f"]